### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Suleman-Elahi** [choraria/gas-url-shortener#17]
The final short URL doesn't work !!
DNS settings are okay I think.

![image](https://user-images.githubusercontent.com/24384996/66897889-99fd3b00-f015-11e9-939c-5c1aca988849.png)

My DNS Settings:
![image](https://user-images.githubusercontent.com/24384996/66898889-a8e4ed00-f017-11e9-8fa6-a59d11dc1e35.png)

**Comment by choraria** [comment]
@Suleman-Elahi - its worked for me :)

![ilovefreesw](https://raw.githubusercontent.com/schoraria911/gas-url-shortener/staging/imgs/ilovefreesw.gif)

I would also recommend [Securing your GitHub Pages site with HTTPS](https://help.github.com/en/articles/securing-your-github-pages-site-with-https).

**Comment by choraria** [comment]
Looks like the issue was with the DNS propagation 😊

**Comment by Suleman-Elahi** [comment]
Indeed it was the problem with the Freenom DNS, I think it takes longer time in propagation for free domains. I shouldn't have opened an issue for that, so I am sorry for that :{
It was a good topic for my blog(ilovefreesoftware.com), I was just doing a tutorial on it.

**Comment by choraria** [comment]
@Suleman-Elahi - Don't worry about it :) I'm anyways happy as you're the first user for this! Keep the feedback flowing too.

**Comment by saxobroko** [comment]
Use cloudflare for near instant dns propagation
