### ISSUE TITLE
When creating a link without http:// or https:// it doesn't work

### ISSUE THREAD

**Issue by saxobroko** [choraria/gas-url-shortener#19]
Eg, https://saxob.ga/bug
If you don't put http:// or https:// before a link it will show up as an error

**Comment by choraria** [comment]
@saxobroko - thanks for reporting this. I was able to replicate this too. Looks like I didn't test it well enough to having caught it during my testing phase 😅

Will try and release a fix as soon as possible; alternately, you're free to recommend modifications in my code too!

**Comment by choraria** [comment]
Found this reference that could help with a solution - https://stackoverflow.com/questions/29684740/javascript-window-open-without-http

**Comment by choraria** [comment]
@saxobroko - here's the fix: #23
